version: '3'

services:
  frontend:
    image: docker-repo.iliyandimitrov.com/v2-portfolio-website-ui:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.portfolio-website.rule=Host(`www.v2.iliyandimitrov.com`) || Host(`v2.iliyandimitrov.com`)"
      - "traefik.http.routers.portfolio-website.entrypoints=websecure"
      - "traefik.http.routers.portfolio-website.tls=true"
      - "traefik.http.services.portfolio-website.loadbalancer.server.port=3000"
    networks:
      - traefik_default

  self-hosted-runner:
    image: docker-repo.iliyandimitrov.com/v2-portfolio-website-runner:latest
    restart: unless-stopped
    networks:
      - traefik_default
networks:
  traefik_default:
    external: true
