name: Frontend Build

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build Frontend
        run: |
          ./infra/docker/frontend/build-docker.sh
          curl ${WEBHOOK_URL} -X GET
