name: Frontend Build

on:
  push:
    branches:
      - 'master'
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build Frontend
        run: |
          cd infra/docker/frontend && ./build-docker.sh
          curl -k -X POST "${V2_PORTFOLIO_WEBSITE_WEBHOOK}"
