name: Frontend Build

on:
  push:
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build Frontend
        run: |
          cd infra/docker/frontend && ./build-docker.sh
          curl -k -X POST "${WEBHOOK_URL}"
