name: Frontend Build

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Build Frontend
      run: |
        cd frontend
        npm install
        npm run build
